### ISSUE TITLE
Dropbox Sync fails with 400 Bad Request

### ISSUE THREAD

**Issue by KatrinIhler** [johannesjo/super-productivity#3436]
I have a similar problem to #2352 and maybe #3288. 

I currently have two SuperProductivity installations (both 10.0.4 right now) on an Ubuntu 24.04 and Fedora 39 respectively. I think this problem occurred first with 10.0.0 for me, but I'm not a 100% sure. Sync works initially but later fails with "Unknown Sync Error: Error: AxiosError: Request failed with status code 400". This mostly seems to happen when switching between the devices or restarting SuperProductivity on one device. Sync can be fixed temporarily by getting a new access token from Dropbox, but the issue will reoccur later.

I followed the instructions in the first issue (exported data locally, deleted data in Dropbox, moved data folder on both devices to get a clean installation, re-imported file on one device and synced it via Dropbox onto the other after reconfiguring sync) but that didn't do the trick for me.

Attached log: [dropbox_error_sp.log](https://github.com/user-attachments/files/16962128/dropbox_error_sp.log) Feel free to request more details.

The following order of actions seems to break pretty reliably for me:
1. Fix error on device A by setting new access token -> sync works.
2. Make change on Device B and sync change up, sync on Device A to get change -> successful, sync still works.
3. Restart SP on Device A - sync error reoccurs.
4. Rinse, repeat...

The change synced from Device B seems to be essential for this, without it the sync still works after an SP restart on A. In the test case, A was the Ubuntu device, but I've seen the error on Fedora as well.

I currently don't have compression and encryption turned on (though I tried the first for a bit before clearing the data from dropbox, not sure if that's relevant). I uninstalled the Android app that I previously also had to ensure that it wasn't causing this somehow, but the problem persists. "Bypass for Network" for the Service Workers doesn't seem to be it either... I'm running out of things to try. ¯\_(ツ)_/¯

**Comment by KatrinIhler** [comment]
Alright, I did some more research. There seems to be something funky happening to the access tokens when the error occurs. Some examples:
Working on Device B:
```
    "rev": "01621d60007748f00000002a3164fe1",
    "lastSync": 1726052843048,
    "revTaskArchive": null,
    "accessToken": "sl.B8sbB_1-grpVAPRdnW5rnutQw50d4uovqtQ0rpeSOeDTehCIsRtct9CFicav8M-mvDjUfxJmOvwg-HpYMDIjaZ4wLypoO-yKiWRt9YMY0CgwxfyQi0wtZNYqqzSwHODr7rDCu04G9GHyecU",
    "_tokenExpiresAt": 1726067264608,
    "refreshToken": "Xx22Hf36jOEAAAAAAAAAAS5ZUArxjVx1wNvrotTap9ErcY01EB3df48fsEHmFYQJ"
    ```

Working on Device A:
```
    "rev": "01621d5ce4d401600000002a3164fe1",
    "lastSync": 1726052028480,
    "revTaskArchive": null,
    "accessToken": "sl.B8sRvrlyPDfw3ZgAke-GX2DEEje1rB68kgC-13ReXorp6fZCH6dPu8-QNnuv2oe6F3Jx2vCF416vC8rT72xdkP-54JAIl_g6-uabbF-CIbgNXcJFSN__9Eum0Q9sP0R3eLI0VAsniikOFUo",
    "_tokenExpiresAt": 1726067393905,
    "refreshToken": "zTo5pxd-hasAAAAAAAAAAQZXi7exQSnajijuDbAu0DsmSXdBq8awVwXXHOOwCt_g"
```

Device A after syncing (where did the Access Token go??):
```
    "rev": "01621d61d73ed4700000002a3164fe1",
    "lastSync": 1726053354450,
    "revTaskArchive": "01621d5272b715400000002a3164fe1"
```

Device A after restart & error (suddenly access token is much longer?)
```
    "rev": "01621d61d73ed4700000002a3164fe1",
    "lastSync": 1726053354450,
    "revTaskArchive": "01621d5272b715400000002a3164fe1",
    "accessToken": "sl.u.AFGew88AYSA7vqintPziOahEJyXaXzPhxLtYM9TtELtyAp86lGUl6JlzExK7pUIOLuqV3K6jA5ZAJkw-cY-folkGUi1DI1DrsQHhXWXPo7l08X_s28rtw7Do8xTl1Aa5xJULID_FiM65xOW3HGn75zKTzmkFJFSnzx24NIfURM3YWo8hwApgYwjO8vr4az17hpavyMwZz-_WpJPozZjSrG6oFctD0LqBA_qGDO1dU6gOmjNCR8PXDIGD_-ztDzmgIvL_FHUWujmmpYuNC3SjNwIaDwvV4OAflayFtaVTmitmy3yRY0oKBD7-PxH1CX041WCurRuw84hkRUo5alvBsclfjEAjEJMX_0gJhST_t6eut8e7PtiHFUmNBfIZdL8sDAwM_Hagzvq2pPps4xPy8WhL0hjo_Cx5tdo3qgXYAUEpNp6rUrYc8XEEn8gL2IyeIM-oTLbk-oI-IDhTj9kzRMwmFXO6WZzITRDvPbsIJuZxNDjlkwCAuYBQstnhpy4lSekwX1cRYRcq2lIKXCyyvTXPyf8kWTakOUlSwOgcFOaF7Xth25F3BxP3Q3-GJAfdyMSD7sBsG4ZXKjRNyPUZbUsN776UxUbpev8ezBLIno-gsyMDCvcQeL4AJ-KevU2S1o6Hu9VLm7Jd0aqK-YaYWP8ZTzbA1vDfDeNBgTGJ7q4uW_sI7GH3_kgLhopf9BUXTztW5od1Gs6NfGjwFX1BRW5MbbxNm4hfD1AL-bME3QoLxpAfleqBxGCryHE7wYa-d78dlC7IlLuFmwNsCYct3VjgSs9F7fKKhlsJv_2z_hJFxm7GKRZfLMu3pOz-Ca_vbjfpx7cdAq45Tr8mUmjzcXbo8dEmb5TSCPAqeRaIkPUNcoT62NZevEnttgryNsJq7dS4rkSNOfWDMB0WCL-oMEb36mPfbxS8CgLEsCqUkuJ0-xlw29Qzxwjv_rJ9RJeOmUy1E5YjtR2e01LliRYrmq2NxotdAAN7TDeEwnrocMNloS8sjrl_pr77X6oPcMXHdkYN4Ds0GgoI_-4NBdxPEpV1r9fjJlIGwxhPe527bEl2xIFzeWjYMGtoJE40HJ3tibP2926fIgqaaJCxSbnbgnWvSZtwQXrwZwRGJInmZoJzseYoNCEfb_PoV0o-C1dwo8GqSDyvNzVLKg66dCoRfoKZ94d4P-RTSHvQnwy-JAl8rCLufiU96tHmG6iIH7I9SA9qAQgtSLowaTvreXAlAXj8Q3R_ZcUsvJXHPJVZApT9MaBVrv_dBeo1DB_lqbtXZBA",
    "_tokenExpiresAt": 0,
    "refreshToken": "MSzpvuXHGxMAAAAAAAAAAYM1jHnAXLu-Cr8DrfKo0_jCNxLIeNbrqWrWW5SF4hJG"
```

Device B after restart and error (same here):
```
    "rev": "01621d61d73ed4700000002a3164fe1",
    "lastSync": 1726053354450,
    "revTaskArchive": null,
    "accessToken": "sl.u.AFGew88AYSA7vqintPziOahEJyXaXzPhxLtYM9TtELtyAp86lGUl6JlzExK7pUIOLuqV3K6jA5ZAJkw-cY-folkGUi1DI1DrsQHhXWXPo7l08X_s28rtw7Do8xTl1Aa5xJULID_FiM65xOW3HGn75zKTzmkFJFSnzx24NIfURM3YWo8hwApgYwjO8vr4az17hpavyMwZz-_WpJPozZjSrG6oFctD0LqBA_qGDO1dU6gOmjNCR8PXDIGD_-ztDzmgIvL_FHUWujmmpYuNC3SjNwIaDwvV4OAflayFtaVTmitmy3yRY0oKBD7-PxH1CX041WCurRuw84hkRUo5alvBsclfjEAjEJMX_0gJhST_t6eut8e7PtiHFUmNBfIZdL8sDAwM_Hagzvq2pPps4xPy8WhL0hjo_Cx5tdo3qgXYAUEpNp6rUrYc8XEEn8gL2IyeIM-oTLbk-oI-IDhTj9kzRMwmFXO6WZzITRDvPbsIJuZxNDjlkwCAuYBQstnhpy4lSekwX1cRYRcq2lIKXCyyvTXPyf8kWTakOUlSwOgcFOaF7Xth25F3BxP3Q3-GJAfdyMSD7sBsG4ZXKjRNyPUZbUsN776UxUbpev8ezBLIno-gsyMDCvcQeL4AJ-KevU2S1o6Hu9VLm7Jd0aqK-YaYWP8ZTzbA1vDfDeNBgTGJ7q4uW_sI7GH3_kgLhopf9BUXTztW5od1Gs6NfGjwFX1BRW5MbbxNm4hfD1AL-bME3QoLxpAfleqBxGCryHE7wYa-d78dlC7IlLuFmwNsCYct3VjgSs9F7fKKhlsJv_2z_hJFxm7GKRZfLMu3pOz-Ca_vbjfpx7cdAq45Tr8mUmjzcXbo8dEmb5TSCPAqeRaIkPUNcoT62NZevEnttgryNsJq7dS4rkSNOfWDMB0WCL-oMEb36mPfbxS8CgLEsCqUkuJ0-xlw29Qzxwjv_rJ9RJeOmUy1E5YjtR2e01LliRYrmq2NxotdAAN7TDeEwnrocMNloS8sjrl_pr77X6oPcMXHdkYN4Ds0GgoI_-4NBdxPEpV1r9fjJlIGwxhPe527bEl2xIFzeWjYMGtoJE40HJ3tibP2926fIgqaaJCxSbnbgnWvSZtwQXrwZwRGJInmZoJzseYoNCEfb_PoV0o-C1dwo8GqSDyvNzVLKg66dCoRfoKZ94d4P-RTSHvQnwy-JAl8rCLufiU96tHmG6iIH7I9SA9qAQgtSLowaTvreXAlAXj8Q3R_ZcUsvJXHPJVZApT9MaBVrv_dBeo1DB_lqbtXZBA",
    "_tokenExpiresAt": 0,
    "refreshToken": "MSzpvuXHGxMAAAAAAAAAAYM1jHnAXLu-Cr8DrfKo0_jCNxLIeNbrqWrWW5SF4hJG"
```

All of these are taken from the log under `Dropbox`. Hope this helps... and now I gotta go do some "real" work before I get fired or something. :laughing:

**Comment by johannesjo** [comment]
@KatrinIhler sorry I deleted your comment since it is potentially dangerous to post your accessToken here.

I'll check the issue.

**Comment by johannesjo** [comment]
Thank you very much @KatrinIhler for digging into this! This was very very helpful! I really appreciate that you risked your job for this!! 🙏😄

So I played around a little and was indeed able to reproduce the error when a very long token string is provided. Reading from the logs I gathered that the problem might be some left over legacy tokens. You should be able to delete those directly using data export and then import (search for `accessToken` under `dropboxSync` and set it to null).

I will delete the legacy mechanism as it was just there to provide users with a better experience while switching versions of SP. I hope this will stop the issue from reoccurring for future versions of SP, even though it might lead to some people having to redo the authentication process.

What I am not quite sure about is why this reoccurs even when the token was reset, since in that case the legacy token shouldn't have been used unless all local data was completely deleted and the legacy token was imported from a file or remote.

**Comment by TheoOliveira** [comment]
Hello. I used SP years ago and now I am trying again sinc now has sync with dropbox. Using it and obsidian for note taking. Thanks for the hard work.

I am facing this issue on a android and arch distro. Did you implement the fix, if you point me the files related i can try to PR

**Comment by johannesjo** [comment]
Fixed version is out now (or will be soon for MS store version).

**Comment by KatrinIhler** [comment]
Unfortunately 10.06 doesn't quite fix this for me. Even for a fresh install, Dropbox sync no longer works because SP doesn't ask for an access token (access and refresh token are null in the config), sync just runs forever.

In case of my data, the legacy token still seems to be part of it, since there is a dropboxSync object next to sync as well as in it, with the latter containing the legacy token and the former the shorter one. Since the new data only creates the dropboxSync object in (!) the sync object, but then doesn't fill it, maybe the code is getting those two places mixed up?

**Comment by KatrinIhler** [comment]
No, actually, I take that back, that's only a temporary fix. Refresh and access token are wiped from LOCAL_NON_SYNC again on sync to or from remote (not sure yet), maybe by _setLocalRevsAndLastSync()? And that causes the original problem except it's now harder to get out of. :sweat_smile:

**Comment by johannesjo** [comment]
Hey @KatrinIhler ! Thank you very much for checking again. I provided a new fix. Could you maybe check again on the test instance:
https://test-app.super-productivity.com/

**Comment by johannesjo** [comment]
Hey @KatrinIhler ! Thank you very much for checking again. I provided a new fix. Could you maybe check another on the test instance:
https://test-app.super-productivity.com/

I am very sorry for the ongoing difficulties with this :/

**Comment by KatrinIhler** [comment]
That looks like a good idea. Gonna test this soon-ish, for now I've moved back to 10.0.04 and I'm trying to track down the initial problem. And I think I might have found it - or am at least on the right track. The problem is that the access token & refresh token the dropbox api service uses lives in LOCAL_NON_SYNC, which gets wiped with the rest of the database when importing data from remote (in a function aptly named clearDatabase()). The tokens are not restored afterwards either. However I'm still uncertain about how this is _supposed_ to work - maybe you can chime in here with the general ide behind this?

**Comment by svennd** [comment]
> Hey @KatrinIhler ! Thank you very much for checking again. I provided a new fix. Could you maybe check another on the test instance: https://test-app.super-productivity.com/
> 
> I am very sorry for the ongoing difficulties with this :/

Atleast this work for me. (the current web-app) doesn't ask for the dropbox auth key. The test-app does!

**Comment by johannesjo** [comment]
Thank you @KatrinIhler for digging into this once more! You're right! That the local sync model stuff is overwritten is the main problem. I just never recognized it, because of the legacy token mechanism. I triggered a new release which should be available shortly and hopefully will fix this issue for good.

**Comment by KatrinIhler** [comment]
Sorry, didn't manage to test yesterday, but I just updated to 10.0.09 and it looks like that indeed fixed my original problem :tada:
