### ISSUE TITLE
Error in Syncing via dropbox

### ISSUE THREAD

**Issue by mbostanara** [johannesjo/super-productivity#414]
Hi,

from yesterday, my dropbox sync fails. I tried to set the settings again and here is the error I get.

![image](https://user-images.githubusercontent.com/62683393/85913544-1c165280-b879-11ea-802d-5df098c895d1.png)

version:5.4.1

**Comment by johannesjo** [comment]
Thank you very much for reporting! Sorry to hear that. The support people at Dropbox promised me that at least existing tokens would not be affected. I think I found the source of the error for new tokens already and will provide a fix asap.

**Comment by Drchen-AI** [comment]
this problem occured !

**Comment by johannesjo** [comment]
@Drchen-AI a fix should be already out. Have you tried the most recent version?

**Comment by mbostanara** [comment]
Thank you, @johannesjo! I checked it again now. It is resolved. I could again turn my dropbox sync on.

**Comment by Drchen-AI** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I don’t know why, but I still have this problem, I use the latest version on Mac.
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                idiotprofessorchen
                            
                    
                        
                            
                                    idiotprofessorchen@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 07/1/2020 17:02，Johannes Millan<notifications@github.com> wrote： 



@Drchen-AI a fix should be already out. Have you tried the most recent version?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by johannesjo** [comment]
@Drchen-AI are you using  version 5.4.1 or 5.4.2? You should find the version number on the global settings page.

**Comment by Drchen-AI** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    yes，I am using version 5.4.2
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                idiotprofessorchen
                            
                    
                        
                            
                                    idiotprofessorchen@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 07/2/2020 16:05，Johannes Millan<notifications@github.com> wrote： 



@Drchen-AI are you using  version 5.4.1 or 5.4.2? You should find the version number on the global settings page.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by johannesjo** [comment]
@Drchen-AI could you also try the 5.4.3 pre release please?

**Comment by Drchen-AI** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    I will take a try, thank u.
    
      
    
    
 
    

    On 07/2/2020 18:29，Johannes Millan<notifications@github.com> wrote： 



@Drchen-AI could you also try the 5.4.3 pre release please?

**Comment by johannesjo** [comment]
Is this still an issue?

**Comment by johannesjo** [comment]
I am closing this due to inactivity. Please let me know if the issue persists with the most recent version.
