### ISSUE TITLE
Error: RangeError: Invalid array length

### ISSUE THREAD

**Issue by QuentinGruber** [johannesjo/super-productivity#463]
### Steps to Reproduce
1. create a task
2. write "h" in estimate time or time spend 

### Console Output
main.537ceab2d6dcf7127421.js:1 GLOBAL_ERROR_HANDLER RangeError: Invalid array length
    at t.setDots (main.537ceab2d6dcf7127421.js:1)
    at t.setRotationFromValue (main.537ceab2d6dcf7127421.js:1)
    at t.onInputChange (main.537ceab2d6dcf7127421.js:1)
    at main.537ceab2d6dcf7127421.js:1
    at _a (main.537ceab2d6dcf7127421.js:1)
    at i (main.537ceab2d6dcf7127421.js:1)
    at e.o [as _next] (main.537ceab2d6dcf7127421.js:1)
    at e.__tryOrUnsub (main.537ceab2d6dcf7127421.js:1)
    at e.next (main.537ceab2d6dcf7127421.js:1)
    at e._next (main.537ceab2d6dcf7127421.js:1)

### Stacktrace
```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:53:12)
handleError (webpack:///node_modules/@angular/core/fesm5/core.js:9066:33)
listenerFn (webpack:///node_modules/@angular/core/fesm5/core.js:14938:8)
getComponentLViewByIndex (webpack:///node_modules/@angular/core/fesm5/core.js:14970:21)
function (webpack:///node_modules/@angular/core/fesm5/core.js:25527:16)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:192:15)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:130:21)
_next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:76:25)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
observers.slice (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:47:24)
```

### Meta Info
META: SP5.5.2 Electron – fr – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.2 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

**Comment by johannesjo** [comment]
Thanks for opening this up! 

What string did you enter exactly? And where exactly. Did you put in the task title (short syntax) or in the time estimation dialog?

**Comment by QuentinGruber** [comment]
Hi, it happened when I wrote "h" alone on "time spent" or "estimated" on this menu.
![image](https://user-images.githubusercontent.com/47059878/88741588-586ef400-d140-11ea-9014-5d440604a0ba.png)

**Comment by johannesjo** [comment]
Ahhh. Alright, thank you very much! I look into it!

**Comment by johannesjo** [comment]
Thanks again. This should be fixed with the next release. Please let me know if it isn't.

**Comment by klangthomas** [comment]
Typed a negative estimate entry by accident (-4m). Still crashes with identical error message

**Comment by johannesjo** [comment]
Thanks @klangthomas ! Should be fixed now!
