### ISSUE TITLE
💥 Recurring tasks don't appear in Today or Schedule.

### ISSUE THREAD

**Issue by lycalys** [johannesjo/super-productivity#4985]
### Steps to Reproduce

1. Make a recurring task for every day.
2. Finish it, move on to next day.
3. The next day the task is missing. It can be seen on the Planner, but can't be completed or anything.

### Url
https://localhost/#/scheduled-list

### Meta Info
META: SP14.3.3_L2A __ Browser – en-GB – Linux aarch64 – en-GB – UA:Mozilla/5.0 (Linux; Android 15; CPH2551 Build/AP3A.240617.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/139.0.7258.94 Mobile Safari/537.36

### Actions Before Error
```

```

**Comment by lycalys** [comment]
It was resolved by closing and reopening the app.

**Comment by vitobotta** [comment]
Can you reopen this issue? It's clearly a bug that should be addressed. I don't think we are expected to close and reopen the app for repeated tasks to appear in the Today view.

**Comment by johannesjo** [comment]
> Can you reopen this issue? It's clearly a bug that should be addressed. I don't think we are expected to close and reopen the app for repeated tasks to appear in the Today view.

I think this has been resolved.

**Comment by vitobotta** [comment]
@johannesjo I still have this issue. I need to close and reopen the app for the repeating tasks to show up in the Today view.

**Comment by johannesjo** [comment]
@vitobotta could you please open up a new issue for this (with all the required meta data)?

**Comment by vitobotta** [comment]
@johannesjo  Sure!
