### ISSUE TITLE
🚨 Missing GUI elements

### ISSUE THREAD

**Issue by Stephane-30** [johannesjo/super-productivity#5111]
### Version Used

15.0.0 Linux

### Expected Behavior

Full display of all GUI elements. I'm using Gnome 48 on Garuda Linux

### Current Behavior

Most GUI elements are missing (not visible). Prior versions to 15.0.0 worked perfectly well.

<img width="922" height="959" alt="Image" src="https://github.com/user-attachments/assets/f3eb8708-6529-44c1-9872-a247e587d655" />

### Steps to Reproduce

Open SP

### Can you reproduce this reliably?

Yes, I can reproduce it reliably.

### Console Output

```shell

```

**Comment by juantxorena** [comment]
Same error with flatpak, opensuse, kde plasma and Wayland. Here are some logs:
```
[3:0914/190905.222867:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Start app...
LaunchProcess: failed to execvp:
xdg-settings
19:09:05.325                   › Initializing plugin node executor
19:09:05.328                   › { enabled: null, showDevTools: false, mode: 'bottom' }
Gtk-Message: 19:09:05.335: Failed to load module "canberra-gtk-module"
[3:0914/190905.363919:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0914/190905.364035:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Saving backups to /home/juantxorena/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/backups
19:09:05.406                   › Saving backups to /home/juantxorena/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/backups
19:09:05.409 (IdleTimeHandler) › Environment detection: {
  sessionType: 'x11',
  currentDesktop: 'KDE',
  isWayland: false,
  isGnomeWayland: false,
  isSnapEnvironment: false
}
19:09:05.410                   › 🚀 Starting idle time tracking (interval: 5000ms, threshold: 15000ms)
[3:0914/190905.411672:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0914/190905.411758:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0914/190905.411810:ERROR:dbus/bus.cc:408] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
19:09:05.489                   › Overlay hide skipped: window=false, enabled=false
[69:0914/190905.514663:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.515246:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.515623:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.515898:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.516118:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.516819:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.518297:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.519486:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.520072:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.520558:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.521077:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.521275:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.521463:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.521672:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.521875:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.522076:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.522260:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.522443:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.522685:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.522888:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.536361:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.536678:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.536882:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.537089:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.537284:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.537492:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.537700:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.537892:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.538110:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.538292:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.538474:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.538652:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.538860:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.539066:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.539268:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.539477:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.539679:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.540301:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.540611:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.540822:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.541147:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.543360:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.545518:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.550425:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.553676:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.554992:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.555352:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.555644:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.555949:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.556228:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.556569:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.556923:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.557254:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.557549:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.557845:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
[69:0914/190905.558176:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
19:09:05.841                   › Overlay hide skipped: window=false, enabled=false
19:09:05.846                   › No custom styles detected at /home/juantxorena/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/styles.css
[3:0914/190905.883890:ERROR:crypto/nss_util.cc:223] Error initializing NSS with a persistent database (sql:/home/juantxorena/.pki/nssdb): NSS error code: -8126
[69:0914/190906.033619:ERROR:third_party/blink/renderer/core/css/remote_font_face_source.cc:357] NOTREACHED hit. 
19:09:10.416 (IdleTimeHandler) › Testing idle detection methods (one-time initialization)...
19:09:10.417 (IdleTimeHandler) › X11 detected, will use powerMonitor for idle detection
19:09:10.419 (IdleTimeHandler) › powerMonitor idle time: 0ms
19:09:10.419 (IdleTimeHandler) › Idle detection result: 0ms (method: powerMonitor, hasError: false)
19:09:10.419                   › 🔍 Idle check completed in 4ms: 0ms (method: powerMonitor)
19:09:10.420                   › ❌ NOT sending idle time: 0ms (threshold: 15000ms, isQuiting: undefined, method: powerMonitor)
```

**Comment by mtelgkamp** [comment]
I have the same issue as well. With v 15.0.0 and v15.0.1

As as helping point: I also had problems with Chrome and Edge not behaving the way they should (missing UI element styles and Texts). For Edge it was resolved between 140.0.3485.54-1 and 140.0.3485.66-1. For Chrome, I do not have the version numbers where it started working again.

**Comment by johannesjo** [comment]
Hopefully this will be fixed by upgrading electron then.

**Comment by Stephane-30** [comment]
I have Electron 34, 35 and 36 installed but it's still not working. What version should be used?

**Comment by johannesjo** [comment]
> I have Electron 34, 35 and 36 installed but it's still not working. What version should be used?

Within the context of building the project for yourself? You need to checkout the project and then change the electron version there and compile via `npm run dist` .

**Comment by mtelgkamp** [comment]
Release 15.0.3 still does not show all texts:

<img width="245" height="299" alt="Image" src="https://github.com/user-attachments/assets/4707c7b9-69f7-4432-ae3d-aac1ff701389" />

**Comment by johannesjo** [comment]
SInce I am not really able to reproduce this myself, help fixing this would be very welcome!

**Comment by prkos** [comment]
I'm also seeing the same problem, interface buttons seem to be missing text/background, I can't see project names, but can see number of tasks in the sidebar, similar on Settings, sections are showing text, but inside the form items are missing text. I can't even see the version, it's usually text at the bottom.

Everything seems to have been working prior to 15.0.0 I think, it was working for me until Saturday 13 Sep, I think there was an update for Super Productivity and also snap. 

When I install an older version independent from snap (from a .deb file on Ubuntu) it's working but it doesn't pick up the data (projects and tasks).

When I try an AppImage of the new 15.0.3 version the problem is there, messed up interface but data is there.

<img width="1920" height="1054" alt="Image" src="https://github.com/user-attachments/assets/8650955f-1360-4331-a803-5892ba12d2d2" />
<img width="1920" height="1051" alt="Image" src="https://github.com/user-attachments/assets/b20a75ff-5aa0-494f-a971-698a805bb2f9" />
<img width="1922" height="1055" alt="Image" src="https://github.com/user-attachments/assets/5416ac45-fd21-4f09-ab51-9e6a5e9148e6" />

**Comment by prkos** [comment]
I posted more experiences with icons appearing after window size change: 

https://github.com/johannesjo/super-productivity/discussions/5150

**Comment by Stephane-30** [comment]
The problem of not showing the UI properly still persists - even with the latest version. Something must have changed in the code base between version 14.x and 15.x.  I have downloaded the AppImg for 14.5.0 and that works absolutely fine. If I run the 15.0.0 AppImg I have the missing UI elements problem.
Some essential part of the code library must have changed between 14 and 15?

**Comment by mtelgkamp** [comment]
With v15.1.0 everything looks fine for me again. Thank you very much (although you might only have updated the electron version and this has coincidentally solved the problem).

**Comment by mtelgkamp** [comment]
In v15.1.1 the Problem is there again, so it is definitely is related to an electron problem, as the electron dependency update was reverted in 88c1f56510819acc118057d71475422148dd935f due to #5232 and #5235

**Comment by johannesjo** [comment]
Thanks @mtelgkamp ! Not sure if there is a good fix in the current situation for both issues :(

I'll investigate.

**Comment by mtelgkamp** [comment]
Maybe "38.1.2" also has the fix for the gui problem? So changing from "38.1.0" to "^38.1.0" in package.json might help, without breaking it for the wayland users, but I did not test it. If I have some more time available I will try to do some tests on my side with different electron versions, but I will not be able to do so this week.

For me it is fine to use 15.1.0 for the time being.

**Comment by johannesjo** [comment]
That would be great @mtelgkamp ! I'd very much appreciate it, since I am not able to reproduce this issue myself.

I am also working on alternative fix for for #5232 and #5235 . Hopefully this will improve the situation.

**Comment by mtelgkamp** [comment]
Thank you for fixing the wayland problem in 4c563b117e28767e46f878f7a3f3c3c8a714f00a and updating electron to 38.2.2 again in 32bdb4785978332915871bbe58dfd3fcc222b683!

[15.1.3-rc.0](https://github.com/johannesjo/super-productivity/releases/tag/v15.1.3-rc.0) works for me and the wayland fix also works as stated in https://github.com/johannesjo/super-productivity/issues/5232#issuecomment-3382409397. So I will not have look into electron 38.1.2.

**Comment by Stephane-30** [comment]
Hurrah, thank you for getting SP on track again for Linux. I can confirm that [15.1.3-rc.0](https://github.com/johannesjo/super-productivity/releases/tag/v15.1.3-rc.0) is working as expected again. Great work.

**Comment by johannesjo** [comment]
Thank you very much for checking! Will make a release this Friday then, so it hopefully won't trouble people too much during their work if something still breaks.

**Comment by johannesjo** [comment]
I think this should be solved now. Thank you everyone for your patience and for your help! Much appreciated!
