### ISSUE TITLE
🚨 Sync data format seem incompatible

### ISSUE THREAD

**Issue by Leon5x** [johannesjo/super-productivity#5185]
### Version Used

v15.0.3

### Expected Behavior

local file sync on windows (synced with nextcloud client) should be able to sync with webdav sync on android

### Current Behavior

local file sync on windows (synced with nextcloud client) to sync with webdav sync on android throws an error

### Steps to Reproduce

I setup super productivity on my windows pc, used the sync option local file (I already have the nextcloud client installed and wanted to sync it that way)

Then I installed the app on my android phone and wanted to connect it via Webdav.
I selected "Keep remote" files and then got the error:
"The remote sync data is incoherent!
Affected model: pluginUserData"

When setting up the sync with webdav on my pc it works fine, but it seems like a bug that both methods use different formats for syncing.

### Can you reproduce this reliably?

Yes, I can reproduce it reliably.

### Console Output

```shell

```

**Comment by njko39** [comment]
i get same bug, but with error "menuTree". I am syncing  between PC and Android via WebDav (InfiniCloud), also tried via Dropbox, result was same error after a day. I can sync again successfully from my phone, but from PC i keep getting menuTree error. I can't say for sure if it happens only at PC, but i got this error three times, all was on PC

**Comment by darachm** [comment]
I just had the same error message with a very different setup, and fixed it for now:
- I use both Android and browser (Firefox) to access personally-hosted* version of super-producitivity webapp
- I was using the Android app to time track (new concept for me 🙄  thanks so much! 🤗 ), and then sync'd and returned to laptop
- upon sync it had error, I said to use remote, and then it threw the same "The remote sync data is incoherent! Affected model: pluginUserData" erorr
- **what worked was to tell my web browser to completely forget the site, then reload and re-setup the sync information, good as new**
- what didn't work was simply saving a backup of settings on phone app and then importing that in webbrowser webapp

Maybe you can figure out how to re-setup refresh your windows app as well?

**Comment by johannesjo** [comment]
Sorry for this issue there was an oversight on my part about cross-version compatability. I think updating the app to the latest version everywhere you use it, should fix this issue.

**Comment by Leon5x** [comment]
Thanks for looking into this, but it is still not fixed.

I updated SP on windows to 16.1.0 and reinstalled on android to 16.1.0 L2A. Changing the sync on my PC to local file creates a single __meta_ file with everything in it and the android app throws an error when pointed to this directory via WebDAV sync. Changing the sync back to WebDAV on my pc creates 11 files and I am able to sync that with android. So the problem still stands.

By the way: I couldn't find anything on updates on windows and it wasn't on the newest version. Should it auto update?

**Comment by johannesjo** [comment]
> By the way: I couldn't find anything on updates on windows and it wasn't on the newest version. Should it auto update?

No for the exe you need to update manually unfortunately.

Yes, you can't combine webdav sync with file sync since they work a bit different (with webdav we can split up files, with file sync this is not possible). 

It does not work if you use webdav everywhere? What is the error you are encountering?

**Comment by Leon5x** [comment]
And there is also no update notification in the program, right?

Ah okay, then sorry for the misunderstanding. I thought it was clear that the problem was trying to combine webdav and file sync.

It worked with webdav everywhere since the beginning, I just wanted to use filesync and nextcloud client on my pc as it is faster.

**Comment by johannesjo** [comment]
> And there is also no update notification in the program, right?

No, unfortunately not.
