### ISSUE TITLE
🚨 Gitlab created tasks are marked having updates, even though nothing changed

### ISSUE THREAD

**Issue by maciejmatczak** [johannesjo/super-productivity#5518]
### Version Used

v16.3.0 (I think), MS Store

### Expected Behavior

If nothing changes in the linked issue, user should not be prompted to review any updates.

### Current Behavior

I added a Gitlab connector, and for every issue it's polling, even though nothing changes - it does make a "bing!" and hints a task having an updates to review.

### Steps to Reproduce

1. Add Gitlab link
2. Add task from Gitlab's issue
3. Every now and then when polling occures, I am "bing!"'ed

### Can you reproduce this reliably?

Yes, I can reproduce it reliably.

### Console Output

```shell

```

**Comment by maciejmatczak** [comment]
It seems that polling on my side always returns `issueWasUpdated: true`. I am the last person commenting on the issue.

https://github.com/johannesjo/super-productivity/blob/5db60bbf4326d03b28d88412240abd2bfb9da0dc/src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts#L119

Does it mean the 'lastRemoteUpdate', is "last time stamp of other people comments" and `task.issueLastUpdated` (`issue.updated_at` ?) is a true issue's update time stamp?

**Comment by kemsar** [comment]
I believe the issue here is that for some updates, the activity log timestamp can be a few milliseconds after the update timestamp and the code doesn't take into account this delay.

For example, I changed the due date on an issue and the `issue.updated_at` shows as "2026-01-08T03:29:14.653Z". However, the activity log (comments) recorded the update a bit later: "2026-01-08T03:29:14.717Z".

Since the code is comparing the `issue.updated_at` value to the most recent activity in the log (`lastRemoteUpdate`), in these cases `issueWasUpdated` will always be true, even though both timestamps are related to the same update.

I think there are a couple of options for fixing this:

1. Instead of using the activity log (comments) to determine the last update, compare `issue.updated_at` to `task.issueLastUpdated`. This would avoid the latency between the update and the update being logged. This would assume that `issue.updated_at` is the record of truth for any and all updates.
2. Instead of using `issue.updated_at`, use the timestamp on the most recent entry in the activity log. This would assume `lastRemoteUpdate` is the record of truth.

Thoughts?

**Comment by kemsar** [comment]
I implemented the first option to see how it would work and seems to do the trick. I can create a pull request if that's an adequate solution.

**Comment by johannesjo** [comment]
That would be great @kemsar ! Not sure if this is the rigth solution, but let's test it.

**Comment by n-maym** [comment]
I think this isn't fully fixed as I currently have 5 out of ~50 issues constantly getting updates even if nothing was changed.  
Marking the update as checked will bring the change back after the next sync.  
I could provide additional informations on the issues if you tell me what you need to know.

I'm using the latest client from the MS Store.

**Comment by johannesjo** [comment]
Could you have another look @kemsar ?
