### ISSUE TITLE
Dropbox sync occasionally returns 504 error on iOS devices

### ISSUE THREAD

**Issue by reinhart1010** [johannesjo/super-productivity#645]
### Your Environment

* Version used: 6.0.1, Web
* Operating System and version: iOS 14.1
* Desktop Environment:
* Browser Name and version: Safari 14.1

### Expected Behavior
The Dropbox sync should work fine. I have tested this against the web app on Android (not the ones downloaded from Play Store)

### Current Behavior
The app returns **Unknown Sync Error: Error: Request failed with Status 504**.

### Steps to Reproduce (for bugs)

1. Open the web app on Safari
2. Add to Home Screen
3. Go to the app Settings (in PWA) to set up Dropbox sync
4. Try wait for 30 mins to 1 hour and try to synchronize again

### Console Output

Unfortunately, in order to get the console output I need to connect to a Mac device, which I don't have.

### Screenshot

![image](https://user-images.githubusercontent.com/17312341/98012931-4336ef00-1e2c-11eb-9a3d-532a9f5fe72c.png)

**Comment by reinhart1010** [comment]
Update: This issue seems to only occur when the app wants to update the data from the Dropbox server (Remote). Otherwise, it will work normally

**Comment by johannesjo** [comment]
Hi there! Thanks for digging into this. Does this happen a 100% of time when data is being loaded? Or just sometimes?

**Comment by reinhart1010** [comment]
1. When the app is first launched, as long as there are no remote changes, the sync works fine.
2. Otherwise, the error will occur indefinitely.

I also suspect that this also affects the Google Drive sync functionality, as I have experience an "Unknown Sync Error: [Object object]" when syncing with Google Drive on iOS, while it does not occur in the web app on Android (I didn't use the native app due to #434).

**Comment by reinhart1010** [comment]
1. When the app is first launched, as long as there are no remote changes, the sync works fine.
2. Otherwise, the error will occur indefinitely.

I also suspect that this also affects the Google Drive sync functionality, as I have experience an "Unknown Sync Error: [Object object]" when syncing with Google Drive on iOS, while it does not occur in the web app on Android (I didn't use the native app due to #434).

**Comment by johannesjo** [comment]
I tried to reproduce this on Mac OS as I don't have an iPhone available to debug this. Unfortunately, I was unable to do so.

I opened up an issue here:
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/504-when-reading-data/m-p/467507#M23844

I hope they can help us.

**Comment by johannesjo** [comment]
A fix for this should be out with the next release and is ready for testing under https://test-app.super-productivity.com/

Could you maybe check there if the problem still occurs?

**Comment by reinhart1010** [comment]
I am currently planning to test the staging app but it seems there is another layout issue.

![image](https://user-images.githubusercontent.com/17312341/99606907-3f66b780-2a3d-11eb-9348-8c7ba921770e.png)

**Comment by johannesjo** [comment]
@reinhart1010 should be fixed now.

**Comment by reinhart1010** [comment]
The layout issue is still reproducible from test-app.superproductivity.com, while the main app.superproductivity.com does not. Already tried resetting the site data from Safari settings.

**Comment by johannesjo** [comment]
Thanks @reinhart1010 at this point the app.super-productivity.com version might have been the more up to date one. I just updated the test... version as well.

**Comment by reinhart1010** [comment]
I have already tested in 6.1.1 and the issue still persists.

**Comment by johannesjo** [comment]
> I have already tested in 6.1.1 and the issue still persists.

the styling issue or the 504 error or both?

**Comment by reinhart1010** [comment]
The styling issue has been fixed. The 504 error still persists.

**Comment by reinhart1010** [comment]
Upgrading to 6.1.2 and the issue seems have been fixed. I'll be testing a few more times before closing it as fixed.

**Comment by reinhart1010** [comment]
However it still fails with 504 (I guess this is still related to the Service Worker)

**Comment by johannesjo** [comment]
May I ask what version is shown when you navigate to the settings on the mobile app?

**Comment by reinhart1010** [comment]
![Uploading 101236424...]

**Comment by johannesjo** [comment]
> ![Uploading 101236424...]

Seems like something went wrong.

**Comment by reinhart1010** [comment]
![image](https://user-images.githubusercontent.com/17312341/101279347-4ab73280-37f4-11eb-9832-ef210d06c60e.png)

**Comment by johannesjo** [comment]
Thank you! I tested with a mac book air safari and I am able to reproduce this as well. I know what is causing this (the service worker stuff still seems to be active for mac somehow), but I don't have a fix yet.

**Comment by reinhart1010** [comment]
So it seems this is a duplicate of angular/angular#37133

**Comment by WantToLearnJapanese** [comment]
This issue happens also on macOS-Safari.

**Comment by WantToLearnJapanese** [comment]
Just as a workaround, on iOS, we can use "[Alook](https://apps.apple.com/us/app/alook-browser-2x-speed/id1261944766)" which do not suffer from the issue. (This is a paid app $0.99) 

I am very curious about why Alook works.  Aren't all the browsers on iOS just Safari with different skin?

**Comment by Human-Action-Recognition** [comment]
This is **still relevant**

**Comment by ribtoks** [comment]
This issue still persists as of today in the web app on latest iPadOS with latest Safari

**Comment by johannesjo** [comment]
Help with this would be welcome! I currently have no iOS devices available to check this.

**Comment by m4nured** [comment]
Hi Johannes,
What kind of iOS device do you need for checking?
I am thinking about supporting this awesome project by sending you a functional iOS-device. 
Would be an iPhone 6s which runs the latest iOS but has a non-essential defect okay, like stripes on the display or some other. Then I might look for a device on "Kleinanzeigen" in the next weeks. 
Sebastian.

**Comment by MikeMorenoDSP** [comment]
Also getting this issue (504)
iPhone 12 running iOS 15.5 using Safari and Dropbox.
Going to test if there are more alternatives than "Alook Browser".

**Comment by apertur** [comment]
I’m on iPad OS 16.1.1, SP 7.12.0, syncing using Dropbox and created an App Shortcut via Safari to quickly access the app via the home screen. Also have the error code: Unknown sync error. Error: Request failed with status code 504. It also works on the first time, but subsequently fails unless I delete all the cache files in Safari settings related to superproductivity.com and restart Safari. Syncing to Dropbox via my Mac OS Catalina and on Android 12 is okay so far.

**Comment by michaellammers** [comment]
Having the same problem, but mainly here to thank you for this great tool. Been in a week and already loving it!

**Comment by tiropictor** [comment]
can confirm that error is still here, iPad Air 4th gen, iOS 16.2 (20C65), using default browser for PWA added to homescreen, getting "**Unknown Sync Error: Error: Request failed with status code 504**"

Other two devices (Android, using app from f-Droid, and Mac, using mac app downloaded from GitHub) sync perfectly.

**Comment by ITCMA** [comment]
Can also confirm error **"Unknown Sync Error: Error: Request failed with status code 504"** on iOS 16.5 with iPhone 14 Pro and iPad Gen 8. Tested with Chrome, Safari and Firefox Browser. Super Productivity Version v7.13.2. 

macOS Ventura (App Store Version - not the Browser) syncing without any problem. If i try it with Chrome on macOS i see the same error 504.

**Comment by jechogit** [comment]
I still have the same problem, my device is an Iphone 14 pro Max.
