### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by MaximeVredeveld** [johannesjo/super-productivity#74]
After updating I opened the app and (I don't know if it's relevant) I removed 2 tasks, one done and one not done. And then I noticed the app doesn't really work anymore. 

The work view page works though, the rest just doesn't.

![deepinscreenshot_superproductivity_20180407090900](https://user-images.githubusercontent.com/35888581/38452371-862d6cdc-3a43-11e8-85b9-bc49f8d15710.png)
![deepinscreenshot_superproductivity_20180407090914](https://user-images.githubusercontent.com/35888581/38452372-8646a9ea-3a43-11e8-9e04-961082807c56.png)

Great job on the app btw. Most productivity apps are shit, this one is awesome.

**Comment by johannesjo** [comment]
Which version are you using and which type etc? Looks like some sort of build  error to me.

**Comment by MaximeVredeveld** [comment]
version 1.10.9-374 on linux deepin 15.5

I tried reinstalling, didn't fix it.

**Comment by johannesjo** [comment]
I mean did you install the Deb or the snap version?

**Comment by johannesjo** [comment]
I published a new release. Could you please check again?

**Comment by MaximeVredeveld** [comment]
@Morganamilo You're right. I did download it via the releases tab also. Eventually I just installed the 1.8.3 again. 

Just now I downloaded the app again via the releases tab. The settings and help pages are still showing code. The rest works fine now :smile:

**Comment by Morganamilo** [comment]
Ah well this still occurs in the latest version to some extent then. You said it happened after deleting some tasks so my guess is that broke the config file somehow and it's now stuck in an invalid state.

if you move the config to a backup `mv ~/.config/superProductivity{,.bak}` does that stop the error? If so it's probably safe to assume it's a config issue.

**Comment by johannesjo** [comment]
@Morganamilo thanks for digging into this!

@MaximeVredeveld best way to check for a broken configuration is to check the
```
~/.config/superProductivity/Local\ Storage/file__0.localstorage
```
file to see if it is A valid JSON and B if there are some double ID's being used for tasks.

**Comment by MaximeVredeveld** [comment]
@johannesjo I made the file json and it works perfectly fine now. I have no idea if that was exactly what you meant, but it works ;)  Thanks for the patience and help!

**Comment by johannesjo** [comment]
You're welcome. I'm curious. What do you mean, by making the file JSON? Did you rename it?

**Comment by MaximeVredeveld** [comment]
@johannesjo haha yep

**Comment by Morganamilo** [comment]
So you accidentally did what I said and move the data to a "backup" so now SupperProductivity is ignoring it and using a clean version.

**Comment by MaximeVredeveld** [comment]
@morganamilo hahaha if you say so. I have no f*cking idea what I was doing xD

**Comment by Morganamilo** [comment]
Ah well, either way that just about confirms the file got corrupted some how. No idea how though.

**Comment by MaximeVredeveld** [comment]
Me neither. I'm just really happy I can use it properly. It's the first productivity app that actually makes me productive!

**Comment by johannesjo** [comment]
Glad that you like it :) Closing this. If you have any further issues, let me. 

@Morganamilo thanks for your help again! I wasn't even aware that electron saves the application data in the home folder. Definitely good to know!
